### ISSUE TITLE
platform architecture dependency arm64 missing

### ISSUE THREAD

**Issue by hsgreen** [AnatoliyGatt/validate-ip-node#2]
I'm trying to use this module on an NVIDIA Tegra system  with an arm64 architecture but arm64 is not listed in the supported arch parameter in the package.json.

I manually changed it and it does work, so can you add arm64 to the main repository?

**Comment by AnatoliyGatt** [comment]
@hsgreen Done! 👍

**Comment by hsgreen** [comment]
Looks like the fix 2148adac5683c80a24921845f0e16e5cdbc152be was not pushed to the main NPM repository for [validate-ip-node](https://www.npmjs.com/package/validate-ip-node).
